### ISSUE TITLE
可否授权迁徙到xcode平台？

### ISSUE THREAD

**Issue by CregskiN** [wishForget/MiniMineCraft#1]
您好！我是从b站过来的小伙伴，已经在这里完成迁徙 https://github.com/CregskiN/MiniMineCraft-xcode 可否授权我写一个迁徙教程呢？
再次向您的开放共享的精神致敬！最后，祝成功上岸！

**Comment by wishForget** [comment]
可以啊，非常开心您能喜欢本项目！！
